#!/bin/bash

# Install dependencies
apt update
apt install -y curl build-essential libz-dev zlib1g-dev default-jdk gradle

# Build
./gradlew build

# Install GraalVM
if [ "$(uname -m)" = 'x86_64' ]; then
    curl -L -o /tmp/graalvm.tar.gz https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.0.0.2/graalvm-ce-java11-linux-amd64-21.0.0.2.tar.gz
else
    curl -L -o /tmp/graalvm.tar.gz https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.0.0.2/graalvm-ce-java11-linux-aarch64-21.0.0.2.tar.gz
fi
mkdir -p /opt/graalvm
tar -C /opt/graalvm -xzf /tmp/graalvm.tar.gz
export PATH="/opt/graalvm/graalvm-ce-java11-21.0.0.2/bin/:$PATH"
export JAVA_HOME="/opt/graalvm/graalvm-ce-java11-21.0.0.2/"
gu install native-image

# Create native binary
mkdir -p staging
native-image --static -jar build/libs/appl_alg_interpreter.jar
mv appl_alg_interpreter staging/iappl.linux-$(uname -m)
